# Generated by Django 3.2 on 2021-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterValuesEm6400',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tot_active_energy', models.FloatField(blank=True, null=True)),
                ('i_a', models.FloatField(blank=True, null=True)),
                ('i_b', models.FloatField(blank=True, null=True)),
                ('i_c', models.FloatField(blank=True, null=True)),
                ('i_avg', models.FloatField(blank=True, null=True)),
                ('v_ab', models.FloatField(blank=True, null=True)),
                ('v_bc', models.FloatField(blank=True, null=True)),
                ('v_ca', models.FloatField(blank=True, null=True)),
                ('v_ll_avg', models.FloatField(blank=True, null=True)),
                ('v_an', models.FloatField(blank=True, null=True)),
                ('v_bn', models.FloatField(blank=True, null=True)),
                ('v_cn', models.FloatField(blank=True, null=True)),
                ('v_ln_avg', models.FloatField(blank=True, null=True)),
                ('active_pow_a', models.FloatField(blank=True, null=True)),
                ('active_pow_b', models.FloatField(blank=True, null=True)),
                ('active_pow_c', models.FloatField(blank=True, null=True)),
                ('active_power_tot', models.FloatField(blank=True, null=True)),
                ('pf_a', models.FloatField(blank=True, null=True)),
                ('pf_b', models.FloatField(blank=True, null=True)),
                ('pf_c', models.FloatField(blank=True, null=True)),
                ('pf_tot', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('thd_i_a', models.FloatField(blank=True, null=True)),
                ('thd_i_b', models.FloatField(blank=True, null=True)),
                ('thd_i_c', models.FloatField(blank=True, null=True)),
                ('thd_v_an', models.FloatField(blank=True, null=True)),
                ('thd_v_bn', models.FloatField(blank=True, null=True)),
                ('thd_v_cn', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('deviceid', models.PositiveIntegerField(blank=True, db_column='deviceId', null=True)),
            ],
            options={
                'db_table': 'register_values_em6400',
            },
        ),
    ]
